version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=school_db
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - ENVIRONMENT=development
    extra_hosts:
      - "host.docker.internal:host-gateway"